# alacritty.toml

[general]
live_config_reload = true
import = [ "~/.config/alacritty/themes/themes/iterm.toml" ]

[env]
TERM = "alacritty"

[window]
decorations     = "none"

# [window.padding]
# x = 5
# y = 5

[scrolling]
history = 16384

[font]
builtin_box_drawing = false
size                = 18

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style  = "Regular"

[selection]
save_to_clipboard     = true

[mouse]
hide_when_typing = true
